project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    background: "#9900CC"

execution:
  freeze: auto


format:
  html:
    mainfont: Open Sans
    linkcolor: "#FF6600"
    toc: true
    theme: 
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]